services:
  - type: web
    name: kitten-game
    runtime: python
    rootDir: kitten-game
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
